blogicum/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="index"),
    path(
        "posts/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"
    ),
    path("posts/create/", views.PostCreateView.as_view(), name="create_post"),
    path(
        "posts/<int:pk>/edit/",
        views.PostUpdateView.as_view(),
        name="edit_post",
    ),
    path(
        "posts/<int:pk>/delete/",
        views.PostDeleteView.as_view(),
        name="delete_post",
    ),
    path(
        "posts/<int:pk>/comment/",
        views.CommentCreateView.as_view(),
        name="add_comment",
    ),
    path(
        "posts/<int:post_pk>/edit_comment/<int:pk>/",
        views.CommentUpdateView.as_view(),
        name="edit_comment",
    ),
    path(
        "posts/<int:post_pk>/delete_comment/<int:pk>/",
        views.CommentDeleteView.as_view(),
        name="delete_comment",
    ),
    path(
        "profile/<slug:slug>/", views.UserDetailView.as_view(), name="profile"
    ),
    path(
        "edit_profile/", views.EditProfileView.as_view(), name="edit_profile"
    ),
    path(
        "category/<slug:slug>/",
        views.CategoryDetailView.as_view(),
        name="category_posts",
    ),
]

blogicum/blogicum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.urls import include, path, reverse_lazy
from django.views.generic.edit import CreateView


handler404 = "pages.views.page_not_found"

handler500 = "pages.views.server_error"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("pages/", include("pages.urls", namespace="pages")),
    path(
        "auth/registration/",
        CreateView.as_view(
            template_name="registration/registration_form.html",
            form_class=UserCreationForm,
            success_url=reverse_lazy("blog:index"),
        ),
        name="registration",
    ),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("blog.urls", namespace="blog")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

blogicum/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


User = get_user_model()


class PublishedCreated(models.Model):
    is_published = models.BooleanField(
        default=True,
        verbose_name="Опубликовано",
        help_text="Снимите галочку, чтобы скрыть публикацию.",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        blank=False,
        verbose_name="Добавлено",
    )

    class Meta:
        abstract = True

    def __str__(self):
        return self.is_published


class Post(PublishedCreated):
    title = models.CharField(
        max_length=256,
        blank=False,
        verbose_name="Заголовок",
    )
    text = models.TextField(
        blank=False,
        verbose_name="Text",
    )
    pub_date = models.DateTimeField(
        blank=False,
        verbose_name="Дата и время публикации",
        help_text=(
            "Если установить дату и время в будущем — можно делать "
            "отложенные публикации."
        ),
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=False,
        related_name="posts",
        verbose_name="Автор публикации",
    )
    location = models.ForeignKey(
        "Location",
        on_delete=models.SET_NULL,
        null=True,
        related_name="posts",
        verbose_name="Местоположение",
    )
    category = models.ForeignKey(
        "Category",
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        related_name="posts",
        verbose_name="Категория",
    )
    image = models.ImageField(
        upload_to="posts_images",
        blank=True,
        verbose_name="Изображение",
    )

    class Meta:
        verbose_name = "публикация"
        verbose_name_plural = "Публикации"

    def __str__(self) -> str:
        return f'"{self.title}" от {self.pub_date}'

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.pk})


class Category(PublishedCreated):
    title = models.CharField(
        max_length=30,
        blank=False,
        verbose_name="Заголовок",
    )
    description = models.TextField(
        blank=False,
        verbose_name="Описание",
    )
    slug = models.SlugField(
        blank=False,
        unique=True,
        verbose_name="Идентификатор",
        help_text=(
            "Идентификатор страницы для URL; разрешены символы "
            "латиницы, цифры, дефис и подчёркивание."
        ),
    )

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "Категории"

    def __str__(self) -> str:
        return self.title


class Location(PublishedCreated):
    name = models.CharField(
        max_length=30,
        blank=False,
        verbose_name="Название места",
    )

    class Meta:
        verbose_name = "местоположение"
        verbose_name_plural = "Местоположения"

    def __str__(self) -> str:
        return self.name


class Comment(PublishedCreated):
    text = models.TextField(
        blank=False,
        verbose_name="Text",
    )
    author = models.ForeignKey(
        User,
        related_name="comments",
        verbose_name="Автор комментария",
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(
        Post,
        verbose_name="Публикация",
        on_delete=models.CASCADE,
        related_name="comments",
    )

    class Meta:
        ordering = ("created_at",)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.post.pk})

blogicum/blog/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = (
            "author",
        )
        widgets = {
            "pub_date": forms.DateTimeInput(
                attrs={"type": "datetime"},
            )
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)

blogicum/blog/views.py
from django.utils import timezone
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
    ListView,
)
from django.db.models import Count

from .forms import PostForm, CommentForm
from .mixins import (
    CommentLoginRequiredMixin,
    MyLoginRequiredMixin,
    PostLoginRequiredMixin,
    PaginatorHelperMixin,
)
from .models import Post, Category, User, Comment
from .constans import DETAIL_VIEW_PAGINATE_BY


class PostCreateView(PostLoginRequiredMixin, CreateView):
    model = Post
    template_name = "blog/create.html"
    form_class = PostForm
    action = "create"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(PostLoginRequiredMixin, UpdateView):
    model = Post
    template_name = "blog/create.html"
    form_class = PostForm
    action = "edit"


class PostDeleteView(PostLoginRequiredMixin, DeleteView):
    model = Post
    template_name = "blog/create.html"
    form_class = PostForm
    action = "delete"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = PostForm(instance=self.object)
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = "blog/detail.html"
    queryset = Post.objects.select_related("location", "category")

    def dispatch(self, request, *args, **kwargs):
        self.object = get_object_or_404(Post, pk=kwargs["pk"])
        if self.request.user != self.object.author:
            get_object_or_404(
                Post,
                pk=kwargs["pk"],
                is_published=True,
                category__is_published=True,
                pub_date__lt=timezone.now(),
            )
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        context["comments"] = self.object.comments.filter(
            is_published=True,
        ).select_related("author")
        return context


class PostListView(ListView):
    model = Post
    template_name = "blog/index.html"
    ordering = "-pub_date"
    paginate_by = 10
    queryset = (
        Post.objects.filter(
            pub_date__lte=timezone.now(),
            is_published=True,
            category__is_published=True,
        )
        .select_related("location", "category")
        .annotate(comment_count=Count("comments"))
    )


class CommentCreateView(CommentLoginRequiredMixin, CreateView):
    post_id = None
    model = Comment
    form_class = CommentForm
    template_name = "blog/comment.html"
    action = "create"

    def dispatch(self, request, *args, **kwargs):
        self.post_id = get_object_or_404(Post, pk=kwargs["pk"])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = self.post_id
        return super().form_valid(form)


class CommentUpdateView(CommentLoginRequiredMixin, UpdateView):
    model = Comment
    fields = ("text",)
    template_name = "blog/comment.html"


class CommentDeleteView(CommentLoginRequiredMixin, DeleteView):
    model = Comment
    fields = ("text",)
    template_name = "blog/comment.html"


class UserDetailView(DetailView, PaginatorHelperMixin):
    model = User
    slug_field = "username"
    context_object_name = "profile"
    template_name = "blog/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = self.object.posts.select_related(
            "location", "category"
        ).order_by("-pub_date").annotate(comment_count=Count("comments"))
        if self.request.user != self.object:
            posts = posts.filter(
                is_published=True,
                category__is_published=True,
            )
        page_obj = self.paginate_list(posts, DETAIL_VIEW_PAGINATE_BY)
        context["page_obj"] = page_obj
        return context


class EditProfileView(MyLoginRequiredMixin, UpdateView):
    model = User
    fields = (
        "first_name",
        "last_name",
        "email",
    )
    template_name = "blog/user.html"

    def get_object(self, *args, **kwargs):
        return self.request.user

    def get_success_url(self) -> str:
        return reverse("blog:profile", kwargs={"slug": self.object.username})


class CategoryDetailView(DetailView, PaginatorHelperMixin):
    model = Category
    slug_field = "slug"
    template_name = "blog/category.html"
    queryset = Category.objects.filter(is_published=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = (
            self.object.posts.filter(
                pub_date__lte=timezone.now(),
                is_published=True,
                category__is_published=True,
            )
            .select_related("location", "category")
            .order_by("-pub_date")
        )
        context["page_obj"] = self.paginate_list(
            posts, DETAIL_VIEW_PAGINATE_BY
        )
        return context

templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Category: {{ category.title }}
{% endblock %}
{% block content %}
  <h1 class="text-center">New in Category - {{ category.title }}</h1>
  <p class="col-6 offset-3 mb-5 lead text-center">{{ category.description }}</p>
  {% for post in page_obj %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/blog/comment.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit_comment/' in request.path %}
    Edit comment
  {% else %}
    Delete comment
  {% endif %}
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    <div class="col d-flex justify-content-center">
      <div class="card" style="width: 40rem;">
        <div class="card-header">
          {% if '/edit_comment/' in request.path %}
            Edit comment
          {% else %}
            Delete comment
        </div>
        <div class="card-body">
          <form method="post"
            {% if '/edit_comment/' in request.path %}
              action="{% url 'blog:edit_comment' comment.post_id comment.id %}"
            {% endif %}>
            {% csrf_token %}
            {% if not '/delete_comment/' in request.path %}
              {% bootstrap_form form %}
            {% else %}
              <p>{{ comment.text }}</p>
            {% endif %}
            {% bootstrap_button button_type="submit" content="Publicate" %}
          </form>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/blog/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit/' in request.path %}
    Edit publication
  {% elif "/delete/" in request.path %}
    Delete publication
  {% else %}
    Make publication
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
          Edit publication
        {% elif '/delete/' in request.path %}
          Delete publication
        {% else %}
          Make publication 
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <article>
              {% if form.instance.image %}
                <a href="{{ form.instance.image.url }}" target="_blank">
                  <img class="border-3 rounded img-fluid img-thumbnail mb-2" src="{{ form.instance.image.url }}">
                </a>
              {% endif %}
              <p>{{ form.instance.pub_date|date:"d E Y" }} | {% if form.instance.location and form.location.is_published %}{{ form.instance.location.name }}{% else %}Earth{% endif %}<br>
              <h3>{{ form.instance.title }}</h3>
              <p>{{ form.instance.text|linebreaksbr }}</p>
            </article>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Publicate" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
  {{ post.title }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Earth{% endif %} |
  {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        {% if post.image %}
          <a href="{{ post.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
          </a>
        {% endif %}
        <h5 class="card-title">{{ post.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {% if not post.is_published %}
              <p class="text-danger">Post was deleted by administration</p>
            {% elif not post.category.is_published %}
              <p class="text-danger">Category was deleted by administration</p>
            {% endif %}
            {{ post.pub_date|date:"d E Y, H:i" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Earth{% endif %}<br>
            From author <a class="text-muted" href="{% url 'blog:profile' post.author %}">@{{ post.author.username }}</a>in
            category {% include "includes/category_link.html" %}
          </small>
        </h6>
        <p class="card-text">{{ post.text|linebreaksbr }}</p>
        {% if user == post.author %}
          <div class="mb-2">
            <a class="btn btn-sm text-muted" href="{% url 'blog:edit_post' post.id %}" role="button">
              Edit publication
            </a>
            <a class="btn btn-sm text-muted" href="{% url 'blog:delete_post' post.id %}" role="button">
              Delete publication
            </a>
          </div>
        {% endif %}
        {% include "includes/comments.html" %}
      </div>
    </div>
  </div>
{% endblock %}

templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Newsline 
{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/blog/profile.html
{% extends "base.html" %}
{% block title %}
  Profile {{ profile }}
{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Profile {{ profile }}</h1>
  <small>
    <ul class="list-group list-group-horizontal justify-content-center mb-3">
      <li class="list-group-item text-muted">Name: {% if profile.get_full_name %}{{ profile.get_full_name }}{% else %}не указано{% endif %}</li>
      <li class="list-group-item text-muted">Registration: {{ profile.date_joined }}</li>
      <li class="list-group-item text-muted">Role: {% if profile.is_staff %}Administrator{% else %}User{% endif %}</li>
    </ul>
    <ul class="list-group list-group-horizontal justify-content-center">
      {% if user.is_authenticated and request.user == profile %}
      <a class="btn btn-sm text-muted" href="{% url 'blog:edit_profile' %}">Edit profile</a>
      <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Change password</a>
      {% endif %}
    </ul>
  </small>
  <br>
  <h3 class="mb-5 text-center">Users publications:</h3>
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

templates/blog/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Edit rpofile
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Edit profile - {{ request.user }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Publicate" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}